### PR TITLE
Feature/149038 upgrade to v4

### PR DESCRIPTION
**Pull request by Audacia-RhysSmith**
| Action | Done? |
| --- | --- |
| Code compiles and unit tests all pass locally | ✔ |
| Debug/console log code removed | ✔ |
| Commented out code removed | ✔ |
| Unit tests added/updated | ✔ |
| README updated | ✔ |
| Considered: <br /> - Performance <br /> - Security <br /> - Logging | ✔ |
| Licenses of any new/upgraded dependencies checked, with no copyleft dependencies introduced | ✔ |

## Misc

### CODE REVIEW

**Comment by Audacia-RhysSmith** [comment]
Need to re run the project in the new repo as IIRC they were fine before the migration but will make sure that it still builds okay and update the PR template form.

Re run of the tests from pulling the code from this repo.

image

**Comment by Audacia-RhysSmith** [comment]
image
Tests re ran from resolving merge conflict from merging dev into feature branch

**Review by OwenLacey28 — APPROVED** [review]
Looks like all relevant stuff [here](https://documentation.openiddict.com/guides/migration/30-to-40.html) has been considered - nice work!

I'd be happy for ADM to act as a canary project for this, if none exists :)

**Review by richardb355 — APPROVED** [review]
Nice work!

**Pull request merged**
